import { xxPermissions } from "../../uni_modules/xx-XXPermissions/utssdk/app-android";
import { Album, albumUtil } from "@/uni_modules/photo-util";
import Uri from "android.net.Uri";
import { setLocatAlbum, getLocatAlbum } from "@/store/storage.key.uts"
import { globalData } from "@/store/global.data.uts"
import { appConfig } from "../../store/app.config";
import { fileDetailType, matterPageReqType, matterPage, mkdirFileName, tankUploadFile } from "@/logic/tank.movement.uts"
// import { UTSAndroid } from "io.dcloud.uts";
// // import Runnable from "java.lang.Runnable";
// import Thread from "java.lang.Thread";



const permission = [
	"android.permission.READ_MEDIA_IMAGES",
	// "android.permission.WRITE_MEDIA_IMAGES",
	"android.permission.READ_MEDIA_VIDEO",
	// "android.permission.READ_EXTERNAL_STORAGE",
	"android.permission.WRITE_EXTERNAL_STORAGE"
	// "android.permission.WRITE_MEDIA_VIDEO",
	// "android.permission.READ_EXTERNAL_STORAGE", "android.permission.WRITE_EXTERNAL_STORAGE"
]
//   



/**
 * tank app使用的相册实体类
 * 使用相册名称对相册id进行分类
 */
export type tankAlbumType = {
	/**
	 * id
	 */
	id : number;
	/**
	 * 名称
	 */
	name : string;
	/**
	 * 封面照片途径 Url
	 */
	coverPicture : string
	/**
	 *  媒体文件数量
	 */
	count : number;
	/**
	 * 该相册的备份状态
	 * 0：不备份
	 * 1：正在备份
	 * 2：所有文件备份完成
	 * 3：云相册
	 */
	backups : 0 | 1 | 2 | 3
	/**
	 * 如果开启备份，且已经上传至 tank 服务器。就会有该id
	 */
	uuid ?: string
	/**
	 * 所有关联的相册id
	 * 使用名称进行相册分类会造成一个相册拥有多个本地相册的id
	 */
	correlationId : Array<number>

}

/**
 * 相册首页所用的数据
 */
type albumArrayDataType = {

	/**
	 * 读取外部存储需要请求的权限
	 */
	authorizationStatus : boolean

	/**
	 * tank app使用的相册实体类 一个数组梭哈
	 * 存储的内容同 tankData，修改此数组可以间接修改 tankData
	 */
	tankDataOnce : Array<tankAlbumType>
	albumMap : HashMap<number, Array<Album>>
	/**
	 * 已上传了多少个文件
	 */
	upFileCount : number
	/**
	 * 总共需要上传多少个文件
	 */
	allUpFileCount : number
}


/**
 * 相册首页所用的数据
 */
export const albumArrayData = reactive({
	authorizationStatus: true,
	tankDataOnce: [],
	albumMap: hashMapOf(),
	upFileCount: 0,
	allUpFileCount: 0
} as albumArrayDataType)







/**
 * 更新相册列表
 */
export function updAlbumArray() {
	albumArrayData.authorizationStatus = xxPermissions.checkSystemPermissionGranted(permission)
	// console.log("///", albumArrayData.authorizationStatus);
	if (albumArrayData.authorizationStatus) {
		const albumArray : Array<Album> = albumUtil.getAlbum()
		const { tankDataOnce } = albumArrayData
		for (let i = 0; i < albumArray.length; i++) {
			const item : Album = albumArray[i]
			// 关联相册
			const idArr : number[] = []
			item.correlationId.forEach((idVal) => {
				idArr.push(idVal.key)
			})
			const locAlbum = tankDataOnce.find((val, inx) : boolean => {
				if (val["name"] == item.name) {
					tankDataOnce[inx].coverPicture = item.coverPicture
					tankDataOnce[inx].correlationId = idArr
					return true
				}
				return false
			})
			if (locAlbum == null) {
				tankDataOnce.push({
					id: item.id,
					name: item.name,
					count: item.count,
					backups: 0,
					coverPicture: item.coverPicture,
					correlationId: idArr
				} as tankAlbumType)
			}
		}
		// 如果已经登录了 并且打开了备份
		if (globalData.user.uuid != "" && appConfig.backup) {
			getServerAlbumList()
		} else {
			setLocatAlbum(tankDataOnce)
		}
	}
}



/**
 * 获取服务器上的备份相册列表
 */
export function getServerAlbumList() {
	matterPage({
		page: 0,
		pageSize: appConfig.maxPageSize,
		orderCreateTime: 'DESC',
		puuid: appConfig.backupFile.uuid,
		deleted: false,
		orderDir: 'DESC'
	} as matterPageReqType).then((res) => {
		const serverFileArr : Array<fileDetailType> = res.data
		const { tankDataOnce } = albumArrayData
		serverFileArr.forEach((sf : fileDetailType) => {
			const hf = tankDataOnce.find((no : tankAlbumType) : boolean => {
				return no.name == sf.name
			})
			if (hf != null) {
				hf.uuid = sf.uuid
				hf.name = sf.name
				hf.count = 0
				hf.backups = 0
				hf.coverPicture = "https://img-bsy.txrpic.com/preview/element/00/01/30/18/E-1301899-D7EB351E.jpg?imageMogr2/quality/90/thumbnail/!800x%3E"
			} else {
				// tankDataOnce.push({
				// 	id: sf.sort,
				// 	name: sf.name,
				// 	count: item.count,
				// 	uuid: item.uuid,
				// 	backups: 0,
				// 	coverPicture: item.coverPicture,
				// 	correlationId: idArr
				// } as tankAlbumType)
			}
		})
		setLocatAlbum(tankDataOnce)
		console.log("从服务器更新本地相册列表", albumArrayData);
	})
}