
/**
 * 获取登录用户信息
 */
export function getUserInfo() {

	console.log("开始获取用户信息");
	uni.request<any>({
		url: "http://192.168.1.199:7004/v1/user/test-userLogin",
		method: "GET",
		data: {
			id: "99999"
		},
		// header:{
		// 	Cookis:"_ak=614134d9-e887-445a-6611-a4b5ec21ede9"
		// },
		success(res) {
			console.log("1111111获取用户信息", res)
		},
		fail(err) {

			console.log("1111111获取用户信息 失败", err)
		}

	})
}