// import { https, requestOptions } from "@/utils/https.logic.uts"
// import { responseType, } from "@/uni_modules/xx-OkHttp/utssdk/interface.uts"


/**
 * 存储空间实体类型
 */
export type Space = {
	sizeLimit : number;
	totalSize : number;
	createTime : string;
	name : string;
	userUuid : string;
	totalSizeLimit : number;
	updateTime : string;
	sort : number;
	type : string;
	uuid : string;
	user : any | null;
}


/**
 * 用户信息实体类型
 */
export type userInfoType = {
	lastTime : string;
	role : string;
	spaceUuid : string;
	createTime : string;
	avatarUrl : string;
	lastIp : string;
	updateTime : string;
	sort : number;
	uuid : string;
	/**
	 * 空间
	 */
	space : Space;
	username : string;
	status : string;
}

export type IRootType = {
	msg : string;
	code : string;
	data : userInfoType;
}

export type IRootTypeTwo<T> = {
	msg : string;
	code : string;
	data : T;
}
export const loginUrl = "/api/user/login"



export type userLoginRequestOptionType = {
	username : string
	password : string
}
