import { userInfoType } from "../pages/login/login.logic"
import { fileDetailType, updUserInfo } from "@/logic/tank.movement"
import { getAppConfig, getUserInfo, getLocatAlbum } from "@/store/storage.key"
import { appConfig } from "@/store/app.config";
import { albumArrayData } from "@/pages/index/index.data.uts"
// import {uts.sdk.modules.DCloudUniGetSystemInfo.SafeArea} from "uts.sdk.modules.DCloudUniGetSystemInfo.SafeArea"








/**
 * 当前设备窗口信息
 */
type windowInfoType = {
	pixelRatio : number;
	// safeArea : SafeArea;
	// safeAreaInsets : SafeAreaInsets;
	screenHeight : number;
	screenTop : number;
	screenWidth : number;
	statusBarHeight : number;
	windowBottom : number;
	windowHeight : number;
	windowTop : number;
	windowWidth : number;
}




/**
 * tank 的系统信息
 */
export type tankSystemInfoType = {
	downloadDirMaxSize : number;
	copyright : string;
	defaultTotalSizeLimit : number;
	scanConfig : string;
	updateTime : string;
	downloadDirMaxNum : number;
	sort : number;
	uuid : string;
	version : string;
	logoUrl : string;
	deletedKeepDays : number;
	faviconUrl : string;
	createTime : string;
	record : string;
	name : string;
	allowRegister : boolean;
	previewConfig : string;
}







/**
 * 设备信息
 */
type deviceldInfoType = {
	/**
	 * 品牌
	 */
	brand : string
	/**
	 * 认证型号
	 */
	model : string
}



/**
 * 非响应式静态数据
 */
type staticDataTyep = {
	/**
	 * 设备信息
	 */
	deviceld : deviceldInfoType

	/**
	 * 备份文件夹
	 */
	backupFile : fileDetailType
	systemInfo : GetSystemInfoResult
}

/**
 * 静态全局数据
 */
export const staticData : staticDataTyep = {
	backupFile: {
		"createTime": "",
		"deleteTime": "",
		"deleted": false,
		"dir": true,
		"md5": "",
		"name": "",
		"path": "",
		"privacy": false,
		"prop": "{}",
		"puuid": "",
		"size":
			//‍[number]‍
			0,
		"sort":
			//‍[number]‍
			1711696034273,
		"spaceUuid": "",
		"space_name": "",
		"times":
			//‍[number]‍
			0,
		"updateTime": "",
		"userUuid": "",
		"uuid": "",
		"visitTime": ""
	},
	deviceld: {
		model: "",
		brand: ""
	},
	systemInfo: {
		"SDKVersion": "",
		"appId": "__UNI__F508DB9",
		"appLanguage": "zh-Hans",
		"appName": "Tank 相册",
		"appTheme": "light",
		"appVersion": "4.0.31",
		"appVersionCode": "403",
		"appWgtVersion": null,
		"brand": "xiaomi",
		"browserName": "",
		"browserVersion": "",
		"deviceBrand": "xiaomi",
		"deviceId": "4e6765c6-4863-4867-931a-df1ea3b26b69",
		"deviceModel": "24129PN74C",
		"deviceOrientation": "portrait",
		"devicePixelRatio":
			//‍[number]‍
			3.25,
		"deviceType": "phone",
		"language": "zh",
		"model": "24129PN74C",
		"osAndroidAPILevel":
			//‍[Int]‍
			35,
		"osLanguage": "zh",
		"osName": "android",
		"osTheme": "light",
		"osVersion": "15",
		"pixelRatio":
			//‍[number]‍
			3.25,
		"platform": "android",
		"romName": "MIUI",
		"romVersion": "V816",
		"safeArea":
			//‍[⁠uts.sdk.modules.DCloudUniGetSystemInfo.SafeArea⁠]‍
			{
				"bottom":
					//‍[number]‍
					0,
				"height":
					//‍[number]‍
					-37,
				"left":
					//‍[number]‍
					0,
				"right":
					//‍[number]‍
					0,
				"top":
					//‍[number]‍
					37,
				"width":
					//‍[number]‍
					0
			} as SafeArea,
		"safeAreaInsets":
			//‍[⁠uts.sdk.modules.DCloudUniGetSystemInfo.SafeAreaInsets⁠]‍
			{
				"bottom":
					//‍[number]‍
					0,
				"left":
					//‍[number]‍
					0,
				"right":
					//‍[number]‍
					0,
				"top":
					//‍[number]‍
					37
			} as SafeAreaInsets,
		"screenHeight":
			//‍[number]‍
			822,
		"screenWidth":
			//‍[number]‍
			370,
		"statusBarHeight":
			//‍[number]‍
			37,
		"system": "Android 15",
		"ua": "uni-app-x/4.32",
		"uniCompileVersion": "4.32",
		"uniCompileVersionCode":
			//‍[number]‍
			4.32,
		"uniCompilerVersion": "4.32",
		"uniCompilerVersionCode":
			//‍[number]‍
			4.32,
		"uniPlatform": "app",
		"uniRuntimeVersion": "4.32",
		"uniRuntimeVersionCode":
			//‍[number]‍
			4.32,
		"version": "12486",
		"windowBottom":
			//‍[number]‍
			0,
		"windowHeight":
			//‍[number]‍
			806,
		"windowTop":
			//‍[number]‍
			0,
		"windowWidth":
			//‍[number]‍
			0
	} as GetSystemInfoResult
}





/**
 * 响应式全局数据
 */
type globalDataType = {

	/**
	 * tank 的系统信息
	 */
	tankSystemInfo : tankSystemInfoType
	/**
	 * 当前设备的窗口信息
	 */
	windowInfo : windowInfoType
	/**
	 * tank 的登录用户信息
	 */
	user : userInfoType
}
/**
 * 响应式全局数据
 */
export const globalData = reactive({
	// server: "",
	// server: "https://pan.promise.pink:442"
	tankSystemInfo: {
		"downloadDirMaxSize": -1,
		"copyright": "",
		"defaultTotalSizeLimit": -1,
		"scanConfig": "{}",
		"updateTime": "",
		"downloadDirMaxNum": -1,
		"sort": 1708484287421,
		"uuid": "",
		"version": "4.0.2",
		"logoUrl": "",
		"deletedKeepDays": 7,
		"faviconUrl": "",
		"createTime": "",
		"record": "",
		"name": "",
		"allowRegister": false,
		"previewConfig": "{}"
	},
	windowInfo: {
		"pixelRatio": 3,
		"screenHeight": 890,
		"screenTop": 0,
		"screenWidth": 400,
		"statusBarHeight": 39,
		"windowBottom": 0,
		"windowHeight": 890,
		"windowTop": 0,
		"windowWidth": 400
	},
	user: {
		lastTime: "",
		role: "",
		spaceUuid: "",
		createTime: "",
		avatarUrl: "",
		lastIp: "",
		updateTime: "",
		sort: 0,
		uuid: "",
		space: {
			sizeLimit: 0,
			totalSize: 0,
			createTime: "",
			name: "",
			userUuid: "",
			totalSizeLimit: 0,
			updateTime: "",
			sort: 0,
			type: "",
			uuid: "",
			user: null
		},
		username: "",
		status: "",
	}


} as globalDataType)









/**
 * tank app 任务的执行状态
 */
type appTaskStatusType = {
	/**
	 * 备份上传、下载状态
	 * 0：没有备份任务或者备份状态停止
	 * 1：正在备份
	 * 2：备份任务完成
	 * 3: 备份任务完成后 30s 确认关闭
	 */
	backups : 0 | 1 | 2 | 3
	/**
	 * 任务队列工作中？？？
	 */
	taskQueueWorkIng : boolean
}

/**
 * tank app 任务的执行状态
 */
export const appTaskStatus = reactive({
	backups: 0,
	taskQueueWorkIng: false
} as appTaskStatusType)








/**
 * 中央仓库初始化
 */
export function storeInit() {
	// 初始化窗口信息
	const res = uni.getWindowInfo();
	const { windowInfo } = globalData
	windowInfo.windowHeight = res.windowHeight
	windowInfo.windowWidth = res.windowWidth
	windowInfo.screenHeight = res.screenHeight
	windowInfo.screenWidth = res.screenWidth
	windowInfo.pixelRatio = res.pixelRatio

	staticData.systemInfo = uni.getSystemInfoSync()
	console.log(" 设备信息", staticData.systemInfo);


	getAppConfig()
	const { brand, model } = staticData.systemInfo
	appConfig.backupFile.name = `${brand}_${model}`
	if (getUserInfo() != null) {
		updUserInfo()
	}




	albumArrayData.tankDataOnce = getLocatAlbum()
	console.log("执行逻辑成功：仓库初始化", appConfig)
	console.log("执行逻辑成功：仓库初始化", globalData)
	console.log("相册列表", albumArrayData.tankDataOnce);

}