/**
 * 三列布局的样式字符串。减少计算
 */
export const clumn3KeyName = "clumn3Style"



/**
 * 用户信息
 */
export const userInfoKeyName = "userInfo"

/**
 * 系统设置配置文件
 */
export const systemConfigKeyName = "systemConfig"


/**
 * 备份文件夹的服务端信息
 */
export const backupFileKeyName = "backupFile"


/**
 * 任务队列本地存储
 */
export const taskQueueKeyName = "taskQueue"



/**
 * 本地相册列表
 */
export const locatAlbumKeyName = "locatAlbum"