import { tankAlbumType } from "../pages/index/index.data.uts"
import { appConfig, configType } from "@/store/app.config";
import { globalData } from "@/store/global.data.uts";
import { userInfoType } from "../pages/login/login.logic"




/**
 * 用户信息
 */
const userInfoKeyName = "userInfo"
/**
 * 获取用户信息
 */
export function getUserInfo() : userInfoType | null {
	const lUinfo = uni.getStorageSync(userInfoKeyName)
	if (lUinfo != "") {
		const uifo = JSON.parse<userInfoType>(lUinfo as string)
		globalData.user = uifo as userInfoType
		return globalData.user
	}
	return null
}
/**
 * 存储用户信息
 */
export function setUserInfo(data : userInfoType) {
	uni.setStorage({
		key: userInfoKeyName,
		data: JSON.stringify(data)
	})
}









/**
 * 系统设置配置文件
 */
const systemConfigKeyName = "systemConfig"
/**
 * 更新系统设置配置文件
 */
export function getAppConfig() {
	const conf = uni.getStorageSync(systemConfigKeyName)
	if (conf != "") {
		const cobj = JSON.parse<configType>(conf as string)!!
		for (val in appConfig) {
			appConfig[val] = cobj[val]
		}
	}
}
/**
 * 存储系统设置配置文件
 */
export function setAppConfig(data : configType) {
	uni.setStorage({
		key: systemConfigKeyName,
		data: JSON.stringify(data)
	})
}



/**
 * 任务队列本地存储
 */
export const taskQueueKeyName = "taskQueue"



/**
 * 本地相册列表
 */
const locatAlbumKeyName = "locatAlbum"

/**
 * 存储本地相册列表
 */
export function setLocatAlbum(arr : Array<tankAlbumType>) {
	uni.setStorage({
		key: locatAlbumKeyName,
		data: JSON.stringify(arr)
	})
}
/**
 * 获取本地相册列表
 */
export function getLocatAlbum() : Array<tankAlbumType> {
	const res = uni.getStorageSync(locatAlbumKeyName)
	if (res != "") {
		return JSON.parse<Array<tankAlbumType>>(res as string)!!
	}
	return []
}