
import { albumUtil } from "@/uni_modules/photo-util";
import { appConfig, globalData, staticData } from "@/store/global.data"
import Uri from "android.net.Uri";


/**
 * 媒体文件实体类型
 */
export type mediaFileType = {
	/**
	 * id
	 */
	id : number
	/**
	 * 预览状态
	 */
	preview ?: boolean
	/**
	 * 文件类型 我定义的类型
	 */
	type : number
	/**
	 * url
	 */
	url : string
	/**
	 * uri
	 */
	uri : Uri
	/**
	 * 文件的类型 通用的类型
	 */
	ty : string
	/**
	 * 文件上传状态
	 * 0:未上传
	 * 1：等待上传
	 * 2：上传完成
	 */
	status : 0 | 1 | 2

	/**
	 * 文件名
	 */
	name : string
	/**
	 * uuid
	 */
	uuid : string


}



/**
 * 根据相册id查询相册所有内容
 */
export function loadAlbumData(id : Array<number>) : Array<mediaFileType> {
	const arr : Array<mediaFileType> = []
	const { albumDetailClumns } = appConfig
	const value = albumUtil.getAlbumsData(id)





	for (let i = 0; i < value.length; i++) {
		const yNum = i / albumDetailClumns
		const item = value[i]
		const addObj : mediaFileType = {
			id: item.id,
			url: item.url,
			type: item.type,
			status: 0,
			uri: item.uri,
			ty: item.ty,
			name: item.title,
			uuid: ""
		}

		// if (i % albumDetailClumns == 0) {
		// 	arr.push([])

		// }

		arr.push(addObj)

	}
	return arr
}