// #ifdef APP-ANDROID
import View from 'android.view.View';
import Color from 'android.graphics.Color';
// #endif

/**
 * 去除底部小白条
 */
// #ifdef APP-ANDROID
@Suppress("DEPRECATION")
// #endif
export function hideBottomBar() {
	// #ifdef APP-ANDROID
	console.log("----------------------!!!");
	UTSAndroid.getUniActivity()!.getWindow()!.getDecorView().setSystemUiVisibility(
		View.SYSTEM_UI_FLAG_LAYOUT_STABLE
		| View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION
		| View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY
	)
	UTSAndroid.getUniActivity()!.getWindow()!.setNavigationBarColor(Color.TRANSPARENT);
	// #endif
}